### ISSUE TITLE
[Feature] Use external authentication

### ISSUE THREAD

**Issue by avsdev-cw** [turtle0x1/LxdMosaic#171]
Could be done using tokens, HTTP Auth, etc.

Would be useful to be able to pass something in in order to provide single-sign-on behaviour

**Comment by avsdev-cw** [comment]
Didn't see the new PR >_> #168

**Comment by turtle0x1** [comment]
Any particular providers ? Im assuming you don't want facebook :wink: 

LDAP (active directory) I need so I will implement some kind of syncing of a user group at some point

**Comment by turtle0x1** [comment]
by the way @avsdev-cw are you still on 0.6.2 or up to date with master now ?

**Comment by avsdev-cw** [comment]
LDAP would be a good choice.

I was thinking more along the line of being able to pass in a pre-authenticated user. Maybe an ssl key pair?

And I'm tracking the master branch now

**Comment by vsltimkay** [comment]
LDAP would be the perfect choice through perhaps with an overlay so that it's not necessary to create additional POSIX groups to handle permissions within LxDMosaic once / if the authentication moves beyond a binary "you can log in" to "Your containers are X, Y and Z" / "Your available resources are ...." etc,.
