### ISSUE TITLE
Enforce minimum password requirements

### ISSUE THREAD

**Issue by turtle0x1** [turtle0x1/LxdMosaic#290]
Im sure theres a whole composer package but the following will do; 

https://stackoverflow.com/a/10753064/4008082

```
public function checkPassword($pwd, &$errors) {
    $errors_init = $errors;

    if (strlen($pwd) < 8) {
        $errors[] = "Password too short!";
    }

    if (!preg_match("#[0-9]+#", $pwd)) {
        $errors[] = "Password must include at least one number!";
    }

    if (!preg_match("#[a-zA-Z]+#", $pwd)) {
        $errors[] = "Password must include at least one letter!";
    }     

    return ($errors == $errors_init);
}
```

**Comment by abelgomez** [comment]
May I suggest something w.r.t. this? Would it be possible to implement this as password strength indicator  (as some other SW do) and/or as something optional that can be enabled/disabled by an admin rather than as a strict policy?

To be fair, sometimes these requirements are a bit a pain, and in some scenarios (e.g., home deployments) are even a bit nonsensical...

**Comment by turtle0x1** [comment]
Yeah it can be made to be opt in!

**Comment by turtle0x1** [comment]
https://www.includehelp.com/code-snippets/password-strength-checker-in-javascript.aspx

**Comment by abelgomez** [comment]
Maybe "opt out" is better for security 🙂

**Comment by turtle0x1** [comment]
Sounds like a better idea!
