### ISSUE TITLE
Migration Advice?

### ISSUE THREAD

**Issue by AlexanderPlaza** [turtle0x1/LxdMosaic#304]
Hello,

I am looking for migration advice. I currently am running LXDUI (https://github.com/AdaptiveScale/lxdui) on my system that is running my LXD containers. I am wondering if there is any suggestion regarding migration onto LXD mosaic?

**Comment by turtle0x1** [comment]
Welcome :smile: 

What kind of migration advise, setup, workflow or something else entirely?

My first pass at LXDUI (master branch) seems it really doesn't offer much, so for a "real" migration there doesn't seem to be much to bring with you (other than users, but a conversion script feels a little aggressive and wouldn't work to well because of differing password hash algos)

**Comment by turtle0x1** [comment]
@AlexanderPlaza im going to close this now, please feel free to update an ill get back to you!
