### ISSUE TITLE
How can i change 80 port of web ui? I have nginx on this port and them conflicting  

### ISSUE THREAD

**Issue by iqido-systems** [turtle0x1/LxdMosaic#349]
How can i change 80 port of web ui? I have nginx on this port and them conflicting

**Comment by turtle0x1** [comment]
Are you using snap or running in a container?

**Comment by iqido-systems** [comment]
> Are you using snap or running in a container?

Hello. I use snap version.

**Comment by turtle0x1** [comment]
Hi 

you can set the ports using the following commands,

`sudo snap set lxdmosaic ports.http=81 ports.https=444`

Ill it to the read me :smile:

**Comment by iqido-systems** [comment]
Thank you very much! smile

**Comment by xiki808** [comment]
How can I change port for the script installation?

**Comment by abelgomez** [comment]
When installed using the script, LXDMosaic is accessed via Apache (see https://github.com/turtle0x1/LxdMosaic/blob/441228ed613929bd9a140ec9fd452b859058fc2f/examples/install_with_clone.sh#L135 and https://github.com/turtle0x1/LxdMosaic/blob/master/examples/lxd_manager.conf). That's why it is recommended to install it in a container (to avoid conflicts with existing daemons).

Just change the ports in the Apache config (i.e., look at `/etc/apache2/sites-enabled/lxd_manager.conf` :) )
