### ISSUE TITLE
Add features comparison matrix in the docs

### ISSUE THREAD

**Issue by lucrus73** [turtle0x1/LxdMosaic#353]
It would be very useful to newcomers having an unbiased answer to these questions:

- Why should I choose LxdMosaic over lxdui or other similar solutions (if there are any)?
- What can I do with LxdMosaic that I can't do with others?
- What cannot be done with LxdMosaic that can be done with others?
- What kind of support LxdMosaic project provides and how does it compare to others?

More specifically, does LxdMosaic support the following LXD/Linux features? What about others (if at all known)? E.g.

- filesystems and storage types such as ext4, zfs, btrfs, directory, ...
- live migration
- folder sharing between guests
- IDMAPPED mounts (kernel >= 5.12)
- setting resources limits for CPU, disk I/O, network, ... via cgroup v2
- monitoring (maybe integration with third parties monitoring solutions)
- guest console access 
- host network configuration (IPv4 and IPv6)
- firewall configuration
- and so on...

And each cell in the matrix could read "Yes", "No", "Unknown", "Planned for release x.y", "Workaround available", ...

It would be a typical features comparison matrix, very similar to those you can often find on Wikipedia, except in the LxdMosaic docs you don't need to follow Wikipedia rules, so I assume it would be easier to make one.

**Comment by bmullan** [comment]
@lucrus73   I am not part of the LxdMosaic project but I have an opinion on your post.

Although these are good goals I'm not sure its necessary at this stage of LxdMosaic for the project o spend this kind of time.

1. Trying to continuously update/maintain such a chart would be a pain the butt because that would mean tryingto keep an eye on other other projects and what they may have changed etc. understanding what the implications of. those changes mean, then trying to update a "chart".   Those other projects are moving targets themselves. [
2. I'd rather the LxdMosaic development focus on their own feature development/introduction roadmap.
3. If you @lucrus73 or someone else would like to take on the role of maintaining #1 and #2 I am positive that the LxdMosaic project would welcome that!  

Anyway, just  my opinion as I said.   I am a user of LxdMosaic.

**Comment by lucrus73** [comment]
Focusing on the roadmap is great, but if few people know the roadmap (which is itself missing from the docs), few people will be inclined to contribute.

Now if this project is in its first stages where nothing is set in stone yet, then I agree, it's better to write code. But if this project is already being used in production, letting others know what it does right now and where it's going in the near future it's probably more important than adding new features.

If tracking others similar project is too much work (I agree it's not easy), then a simple list of what this project does now, what it is planned to do in the near future and what it might make sense for such a project but there is no plan to implement in the near future would be nearly as useful as the comparison matrix.

**Comment by turtle0x1** [comment]
I've been thinking this one over for a while.

I agree on the need for a feature matrix which is coming in the website (see below).

But I dont feel direct comparisons between LXDMosaic & non-comercial open source software belong as part of the official software / website. I feel its more acceptable to come as a blog post or in a discussion forum where regular updates by others can be provided to stop information getting stale. 

The roadmap isn't clear because there is little to no data to make decisions on. Sometimes you catch big orgs in your emails / the github logs (which implies "enterprise tools") but then the snap installs suggest it's individuals using it (which suggests dev tools) - its hard to know where to put priority. Generally my thinking is "keep up with LXD as best you can, improve the bits you don't like or need more from", outside of this I rely on feedback from users. If there is specific features you'd like, please open an issue for each one and we can discuss.

I'm going to close this as the website will cover most of what your suggesting be done here.

Here are some screenshots of the website (early work, text is horribly bad - dont judge :sweat_smile: );

_Homepage_
![homepage](https://user-images.githubusercontent.com/12494629/144524878-4a1148a0-e165-43d4-82b0-e91dae2618e7.png)
_Feature Matrix_
![features](https://user-images.githubusercontent.com/12494629/144524884-27809ec1-9826-4857-bc72-1ef8a40f2d5a.png)
