### ISSUE TITLE
Time on X axis of graphs not adjusted for timezone

### ISSUE THREAD

**Issue by intrepidsilence** [turtle0x1/LxdMosaic#370]
**Description**
When viewing graphs, the time on the X axis is not adjusted based upon timezone. 

**To Reproduce**
1. The lxdMosaic container (installed using snap) has the correct timezone set.
2. The system where you are using the web browser to view to UI has the correct timezone set
3. Time on X axis appears to be in UTC

**Expected behavior**
Time on the X axis of graphs should be adjusted using the user's timezone data.

**Desktop (please complete the following information):**
 - OS: Linux, Mac
 - Browser: Firefox, Safari
 - Version: Manjaro 21.0.3, macOS 11.3

**Comment by turtle0x1** [comment]
The server should probably always store UTC and then be converted later in the program.

Ive tested it in a container & snap and the time is by default UTC and can confirm the behaviour (and a fix)

Changing this might effect users who have worked around this issue because if they have set the time zone to something else (in php.ini) then the code might incorrectly assume its UTC. (also there will be an over lapping of date times)

There is an issue with crunz in that the time zone is hard coded to Europe/London, it will convert your system to the specified time zone and then run the job according to the time zone, buts wrong for users outside of the UK. Not sure how to work around it in snap, might be tricky because you cant change files.

The to-do list im taking away from this is;

 - [ ] assume all dates are UTC and convert to local browser time
 - [ ] tell php to default to UTC `date_default_timezone_set("UTC");`
 - [ ] document that it should be UTC time server side & users should set their time zone in `crunz.yml` for background jobs like backups

The problem that I might have to look upstream to solve is the setting of the time zone in `crunz.yml` as you cant modify the files in snap but it may be possible to read an environment variable.
