### ISSUE TITLE
Cannot create Cloud Config in web gui. Error message for Create.php 24

### ISSUE THREAD

**Issue by expressrussian** [turtle0x1/LxdMosaic#493]
**Describe the bug**
Cannot Create new Cloud Config in web gui / Cloud Config tab - php error. 1 week after installing LxdMosaic and successfully created 2 cloud configs. Now it is possible to delete a previously created cloud config, but not to create new one.

1. Go to LxdMosaic https web interface, log in.
2. Click on 'Cloud Config' link on the top row. Then click on the blue + button to create a new Cloud Config.
3. Fill in any Name and Namespace fields. Click blue "Create" button.
4. See red error message popup in the top right corner: "Have a cloud config with this name in this namespace /snap/lxdmosaic/132/htdocs/src/classes/Tools/CloudConfig/Create.php 24"
5. I have tried different names/text, but got the same error.

**Expected behavior**
See a new cloud config section created on the left side.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 21H2
 - Browser Firefox 99 x64

**Server:**
 - Device: Intel J1900 Celeron 4 cores
 - OS: Ubuntu 20.04 LTS server x64
 - Lxd and LxdMosaic are installed as snaps:
lxd        4.0.9-8e2046b  22753  4.0/stable/…   canonical✓  -
lxdmosaic  0+git.2124524  132    latest/stable  turtle0x1   -

**Additional context**
What are these links - Projects, Deployments and Cloud Config is not clear and i could not find any information how to use them.
![Capture20220412](https://user-images.githubusercontent.com/45077477/162921890-64806fa0-8492-4cdb-bbb5-159a55deb3a2.JPG)

**Comment by turtle0x1** [comment]
The snap version on `stable` channel is very old, `edge` is much more up to date, ill be pushing an update very soon.

Because this doesn't replicate in the latest version so im going to close this.

# Projects
 -  LXD concept, a way to separate instances / images (think enviornments like `dev`, `prod`, `client1`, `client2`) 
# Cloud Config 
 - LXD / LXDMosaic concept, a way to revision data you would find in `user.user-data` and deploy to instances
# Deployments 
  - LXDMosaic concept, a collection of cloud config files deployed into a "deployment" (a "deployment" could be `apache`, `mysql`, `redis` for example, this code is very old and not really used as far as im aware).

**Comment by expressrussian** [comment]
How do i configure "edge" channel for LXDMosaic, please?
Is it possible to configure it only for LXDMosaic?

**Comment by turtle0x1** [comment]
yea sure, `snap refresh lxdmosaic --edge`
