### ISSUE TITLE
Setting CPU and memory limits

### ISSUE THREAD

**Issue by lhorace** [turtle0x1/LxdMosaic#57]
**Is your feature request related to a problem? Please describe.**
There's a closed PR #41 and #40 that seems to implement what I'm looking for. Though I haven't had a chance to muck around with instance types as it throws me off. Is this LxdMosaic to manage AWS EC2? Ideally, I'd like to set CPU (e.g. 1 or 2 core) and Memory Limits (also soft or hard).

**Describe the solution you'd like**
Able to set cpu and memory limits on container creation and during runtime, similar to how LXDUI does it. 

**Describe alternatives you've considered**
VIA Cli

**EDIT:** It would be neat also if would could edit container YAML and/or expose other limits as well.

**Comment by turtle0x1** [comment]
instance types are available and they limit by the things your asking for, i think you can edit config (i forget which button it is you need to click not by a pc right now)

**Comment by lhorace** [comment]
> instance types are available and they limit by the things your asking for

I'll look into that, though it's not usable if you bypass `instance types` or for existing containers.

> i think you can edit config (i forget which button it is you need to click not by a pc right now)

Looking into it.

**Comment by turtle0x1** [comment]
Settings is what I was I thinking about as you can edit a lot of the config keys (I think i disabled two of them because you need a much bigger text box)

> I haven't find anything regarding editing the RAW YAML config.

Editing the yaml would be to difficult at this time due to the way it would have to be implemented (taking the existing config comparing it to the new one creating a diff and submitting it as an array) 

What I can take away from this is the following features; 

- Allow setting container options a creation time 
- Work towards adding some more the disabled keys as configurable

**Comment by turtle0x1** [comment]
Please test this whenever you can :smile:

**Comment by lhorace** [comment]
This is a perfect compromise and the Dialog is better laid out.

Cheers
